apiVersion: apps/v1
kind: Deployment
metadata:
  name: forecast-alpha-retail-deployment
  labels:
    app: forecast-alpha-retail
spec:
  replicas: 3
  selector:
    matchLabels:
      app: forecast-alpha-retail
  template:
    metadata:
      labels:
        metaclass: executor
        app: forecast-alpha-retail
    spec:
      containers:
        - name: forecast-alpha-retail
          image: gcr.io/modelservice-ase/executor:latest
          args: [ "-p","forecast-alpha","-v","latest","-d","today","-c","retail" ]
          readinessProbe:
            httpGet:
              port: 80
              path: /ready
            initialDelaySeconds: 20
            periodSeconds: 5
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: forecast-alpha-executor-retail-service
  labels:
    apps: forecast-alpha-retail
spec:
  selector:
    app: forecast-alpha-retail
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forecast-alpha-fashion-deployment
  labels:
    app: forecast-alpha-fashion
spec:
  replicas: 3
  selector:
    matchLabels:
      app: forecast-alpha-fashion
  template:
    metadata:
      labels:
        metaclass: executor
        app: forecast-alpha-fashion
    spec:
      containers:
        - name: forecast-alpha-fashion
          image: gcr.io/modelservice-ase/executor:latest
          args: [ "-p","forecast-alpha","-v","latest","-d","today","-c","fashion" ]
          readinessProbe:
            httpGet:
              port: 80
              path: /ready
            initialDelaySeconds: 20
            periodSeconds: 5
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: forecast-alpha-executor-fashion-service
  labels:
    apps: forecast-alpha-fashion
spec:
  selector:
    app: forecast-alpha-fashion
  ports:
    - port: 80
